codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:
        paths:
          - "tests/"
        target: 90%
    patch: false  # disable the patch status